id: A30CA2293
base_file: f6619.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:00:48.736971
  last_modified_at: 2022-05-31 05:00:48.736978
